--ALTER TABLE COMPASS_MI.PTS_MODIFIER DROP PRIMARY KEY CASCADE;
--
--DROP TABLE COMPASS_MI.PTS_MODIFIER CASCADE CONSTRAINTS;

CREATE TABLE COMPASS_MI.PTS_MODIFIER
(
  GUID         RAW(16)                          NOT NULL,
  VERSION      NUMBER(10)                       NOT NULL,
  CODE         VARCHAR2(2 CHAR)                 NOT NULL,
  PTS_GUID     RAW(16),
  DESCRIPTION  VARCHAR2(50 CHAR)                NOT NULL
);

CREATE INDEX COMPASS_MI.IDXPTS_MODIFIERPTS ON COMPASS_MI.PTS_MODIFIER (PTS_GUID);

CREATE UNIQUE INDEX COMPASS_MI.UIDX_PTS_MOD_PTS_GUID ON COMPASS_MI.PTS_MODIFIER (CODE, PTS_GUID);

ALTER TABLE COMPASS_MI.PTS_MODIFIER ADD PRIMARY KEY (GUID);
ALTER TABLE COMPASS_MI.PTS_MODIFIER ADD CONSTRAINT UK_PTS_MOD_PTS_GUID UNIQUE (CODE, PTS_GUID);

ALTER TABLE COMPASS_MI.PTS_MODIFIER ADD (CONSTRAINT FK_PTS_MOD_PTS_GUID
 FOREIGN KEY (PTS_GUID)  REFERENCES COMPASS_MI.PTS (GUID));
