--------------------------------------------------------
--  File created - Thursday-February-03-2022
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICE_EVENT
--------------------------------------------------------

  CREATE TABLE "COMPASS_MI"."SERVICE_EVENT"
   (	"GUID" RAW(16),
	"VERSION" NUMBER(10,0),
	"DURATION_TYPE" VARCHAR2(1 CHAR),
	"START_DATE_TIME" TIMESTAMP (6),
	"SERVICE_EVENT_TYPE" VARCHAR2(50 CHAR),
	"UNITS" NUMBER(6,2),
	"SERVICE_DEFINITION_GUID" RAW(16),
	"AGENT_CUSTOM_SERVICE" RAW(16),
	"STOP_DATE_TIME" TIMESTAMP (6),
	"RECURRENCE_RULES" VARCHAR2(500 CHAR),
	"LINKED_EVENT" RAW(16),
	"UNITS_NOT_PROVIDED" NUMBER(6,2),
	"COST_PER_UNIT" NUMBER(8,2),
	"ORIGINAL_START_DATE_TIME" TIMESTAMP (6),
	"AT_RISK" VARCHAR2(1 CHAR) DEFAULT 0,
	"NOTES_TO_VENDOR" CLOB,
	"REPEAT_UNTIL_DATE_TIME" TIMESTAMP (6),
	"NONSERVICE_REASON" VARCHAR2(2 CHAR),
	"SERVICE_AUTHORIZATION_NUMBER" VARCHAR2(20 CHAR),
	"NONSERVICE_MEMO" CLOB,
        "FREQUENCY" NUMERIC(2),
        "UNITS_PER_DAY" NUMERIC(3),
	"ENTER_DATE" TIMESTAMP (6),
	"ENTER_USER_GUID" RAW(16),
	"ORIGINAL_TEMPLATE_ID" NUMBER(19,0)  
   ) ;
--------------------------------------------------------
--  DDL for Index UK_2B6DTIQJ04F0KINEXG1JSWTXW
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."UK_2B6DTIQJ04F0KINEXG1JSWTXW" ON "COMPASS_MI"."SERVICE_EVENT" ("DURATION_TYPE", "START_DATE_TIME", "SERVICE_EVENT_TYPE", "UNITS", "SERVICE_DEFINITION_GUID", "AGENT_CUSTOM_SERVICE", "RECURRENCE_RULES", "LINKED_EVENT") ;
--------------------------------------------------------
--  DDL for Index IDXSRVC_VNTSRVC_DFNTN
--------------------------------------------------------

  CREATE INDEX "COMPASS_MI"."IDXSRVC_VNTSRVC_DFNTN" ON "COMPASS_MI"."SERVICE_EVENT" ("SERVICE_DEFINITION_GUID", "AGENT_CUSTOM_SERVICE", "LINKED_EVENT") ;
--------------------------------------------------------
--  DDL for Index SYS_C00141628
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."SYS_C00141628" ON "COMPASS_MI"."SERVICE_EVENT" ("GUID") ;
--------------------------------------------------------
--  Constraints for Table SERVICE_EVENT
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("GUID" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("VERSION" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("DURATION_TYPE" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("START_DATE_TIME" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("SERVICE_EVENT_TYPE" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("UNITS" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("SERVICE_DEFINITION_GUID" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("AT_RISK" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("ENTER_DATE" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" MODIFY ("ENTER_USER_GUID" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" ADD PRIMARY KEY ("GUID");

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" ADD CONSTRAINT "UK_2B6DTIQJ04F0KINEXG1JSWTXW" UNIQUE ("DURATION_TYPE", "START_DATE_TIME", "SERVICE_EVENT_TYPE", "UNITS", "SERVICE_DEFINITION_GUID", "AGENT_CUSTOM_SERVICE", "RECURRENCE_RULES", "LINKED_EVENT");
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_EVENT
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" ADD CONSTRAINT "FK_5GRDXW78JOXIOTRA2N7MUQIQB" FOREIGN KEY ("LINKED_EVENT")
	  REFERENCES "COMPASS_MI"."SERVICE_EVENT" ("GUID") ENABLE;

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" ADD CONSTRAINT "FK_JE7OGN2JR6MACQNMYS9GVSEYM" FOREIGN KEY ("SERVICE_DEFINITION_GUID")
	  REFERENCES "COMPASS_MI"."SERVICE_DEFINITION" ("GUID") ENABLE;

  ALTER TABLE "COMPASS_MI"."SERVICE_EVENT" ADD CONSTRAINT "FK_PA80SC20GR3RU1PAM1V3RC750" FOREIGN KEY ("AGENT_CUSTOM_SERVICE")
	  REFERENCES "COMPASS_MI"."AGENT_CUSTOM_SERVICE" ("GUID") ENABLE;
