--ALTER TABLE COMPASS_MI.PTS_FUND_SOURCE DROP PRIMARY KEY CASCADE;
--
--DROP TABLE COMPASS_MI.PTS_FUND_SOURCE CASCADE CONSTRAINTS;

CREATE TABLE COMPASS_MI.PTS_FUND_SOURCE
(
  GUID         RAW(16)                          NOT NULL,
  VERSION      NUMBER(10)                       NOT NULL,
  CODE         VARCHAR2(4 CHAR)                 NOT NULL,
  PTS_GUID     RAW(16),
  DESCRIPTION  VARCHAR2(30 CHAR)                NOT NULL
);

CREATE INDEX COMPASS_MI.IDXPTS_FUND_SRC_PTS_GUID ON COMPASS_MI.PTS_FUND_SOURCE(PTS_GUID);

CREATE UNIQUE INDEX COMPASS_MI.UKIDX_FUND_SRC_PTS_GUID ON COMPASS_MI.PTS_FUND_SOURCE(CODE, PTS_GUID);

ALTER TABLE COMPASS_MI.PTS_FUND_SOURCE ADD PRIMARY KEY (GUID);
ALTER TABLE COMPASS_MI.PTS_FUND_SOURCE ADD CONSTRAINT UK_FUND_SRC_PTS_GUID UNIQUE (CODE, PTS_GUID);

ALTER TABLE COMPASS_MI.PTS_FUND_SOURCE ADD (  CONSTRAINT FK_FUND_SRC_PTS_GUID
 FOREIGN KEY (PTS_GUID)  REFERENCES COMPASS_MI.PTS (GUID));
