--ALTER TABLE COMPASS_MI.PTS_FS_SERVICE_COMBO
-- DROP PRIMARY KEY CASCADE;
--
--DROP TABLE COMPASS_MI.PTS_FS_SERVICE_COMBO CASCADE CONSTRAINTS;
--------------------------------------------------------
--  DDL for Table PTS_FS_SERVICE_COMBO
--------------------------------------------------------

  CREATE TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" 
   (	"GUID" RAW(16), 
	"VERSION" NUMBER(10,0), 
	"START_DATE" TIMESTAMP (6), 
	"PTS_FUND_SOURCE" RAW(16), 
	"PTS_SERVICE_COMBO" RAW(16), 
	"PTS_GUID" RAW(16), 
	"STOP_DATE" TIMESTAMP (6)
   ) ;
--------------------------------------------------------
--  DDL for Index SYS_C0015744
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."SYS_C0015744" ON "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ("GUID") ;
--------------------------------------------------------
--  DDL for Index UK_2AXU33PNYUOMMR7VPRQHCEOBA
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."UK_2AXU33PNYUOMMR7VPRQHCEOBA" ON "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ("START_DATE", "PTS_FUND_SOURCE", "PTS_SERVICE_COMBO", "PTS_GUID") ;
--------------------------------------------------------
--  DDL for Index IDXPTS_FS_SERVICE_COMBOPTS
--------------------------------------------------------

  CREATE INDEX "COMPASS_MI"."IDXPTS_FS_SERVICE_COMBOPTS" ON "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ("PTS_FUND_SOURCE", "PTS_SERVICE_COMBO", "PTS_GUID") ;
--------------------------------------------------------
--  Constraints for Table PTS_FS_SERVICE_COMBO
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" MODIFY ("GUID" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" MODIFY ("VERSION" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" MODIFY ("PTS_FUND_SOURCE" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" MODIFY ("PTS_SERVICE_COMBO" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" MODIFY ("PTS_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ADD PRIMARY KEY ("GUID");
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ADD CONSTRAINT "UK_2AXU33PNYUOMMR7VPRQHCEOBA" UNIQUE ("START_DATE", "PTS_FUND_SOURCE", "PTS_SERVICE_COMBO", "PTS_GUID");
--------------------------------------------------------
--  Ref Constraints for Table PTS_FS_SERVICE_COMBO
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ADD CONSTRAINT "FK_DV1NDI3O9ITW60S7N1M5FX0MF" FOREIGN KEY ("PTS_FUND_SOURCE")
	  REFERENCES "COMPASS_MI"."PTS_FUND_SOURCE" ("GUID") ENABLE;
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ADD CONSTRAINT "FK_ER3K376GY5IASMV53QSH5543W" FOREIGN KEY ("PTS_GUID")
	  REFERENCES "COMPASS_MI"."PTS" ("GUID") ENABLE;
 
  ALTER TABLE "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ADD CONSTRAINT "FK_IULMUU0TPTVW4RRGHGJBD76SF" FOREIGN KEY ("PTS_SERVICE_COMBO")
	  REFERENCES "COMPASS_MI"."PTS_SERVICE_COMBO" ("GUID") ENABLE;
