  CREATE TABLE "COMPASS_MI"."SERVICE_EVENT_INSTANCE" 
   	(
	"SERVICE_DEFINITION_GUID" RAW(16) NOT NULL ENABLE, 
  "SERVICE_EVENT_GUID" RAW(16) NOT NULL ENABLE, 
	"AGENT_CUSTOM_SERVICE" RAW(16), 
	"START_DATE_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"STOP_DATE_TIME" TIMESTAMP (6));
  /
  
   CREATE INDEX "COMPASS_MI"."INDX_SE_INSTANCE_SE_GUID" ON "COMPASS_MI"."SERVICE_EVENT_INSTANCE" ("SERVICE_EVENT_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
/

    CREATE INDEX "COMPASS_MI"."INDX_SE_INSTANCE_SD_GUID" ON "COMPASS_MI"."SERVICE_EVENT_INSTANCE" ("SERVICE_DEFINITION_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
/