--
--ALTER TABLE COMPASS_MI.PTS_SERVICE_COMBO DROP PRIMARY KEY CASCADE;
--
--DROP TABLE COMPASS_MI.PTS_SERVICE_COMBO CASCADE CONSTRAINTS PURGE;
--------------------------------------------------------
--  File created - Monday-July-13-2020
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTS_SERVICE_COMBO
--------------------------------------------------------

  CREATE TABLE "COMPASS_MI"."PTS_SERVICE_COMBO"
   (	"GUID" RAW(16),
	"VERSION" NUMBER(10,0),
	"PTS_PROCEDURE" RAW(16),
	"PTS_MODIFIER" RAW(16),
	"PTS_STANDARD_REMARK" RAW(16),
	"START_DATE" TIMESTAMP (6),
	"PTS_GUID" RAW(16),
	"STOP_DATE" TIMESTAMP (6),
	"SHORT_NAME" VARCHAR2(50 CHAR),
	"PARTICIPANT_SHORT_NAME" VARCHAR2(50 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Index UK_6AYMGAP2F7134JTLJ1YGGQI0X
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."UK_6AYMGAP2F7134JTLJ1YGGQI0X" ON "COMPASS_MI"."PTS_SERVICE_COMBO" ("PTS_PROCEDURE", "PTS_MODIFIER", "PTS_STANDARD_REMARK", "START_DATE", "PTS_GUID") ;
--------------------------------------------------------
--  DDL for Index IDXPTS_SERVICE_COMBOPTS
--------------------------------------------------------

  CREATE INDEX "COMPASS_MI"."IDXPTS_SERVICE_COMBOPTS" ON "COMPASS_MI"."PTS_SERVICE_COMBO" ("PTS_PROCEDURE", "PTS_MODIFIER", "PTS_STANDARD_REMARK", "PTS_GUID") ;
--------------------------------------------------------
--  DDL for Index SYS_C0015431
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."SYS_C0015431" ON "COMPASS_MI"."PTS_SERVICE_COMBO" ("GUID") ;
--------------------------------------------------------
--  Constraints for Table PTS_SERVICE_COMBO
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("GUID" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("VERSION" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("PTS_PROCEDURE" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("START_DATE" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("PTS_GUID" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("SHORT_NAME" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" MODIFY ("PARTICIPANT_SHORT_NAME" NOT NULL ENABLE);

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" ADD PRIMARY KEY ("GUID");

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" ADD CONSTRAINT "UK_6AYMGAP2F7134JTLJ1YGGQI0X" UNIQUE ("PTS_PROCEDURE", "PTS_MODIFIER", "PTS_STANDARD_REMARK", "START_DATE", "PTS_GUID");
--------------------------------------------------------
--  Ref Constraints for Table PTS_SERVICE_COMBO
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" ADD CONSTRAINT "FK_5SVKOJJFIJ6IUJ4ARH6LEMGC6" FOREIGN KEY ("PTS_PROCEDURE")
	  REFERENCES "COMPASS_MI"."PTS_PROCEDURE" ("GUID") ENABLE;

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" ADD CONSTRAINT "FK_BTIPB7P6PWXFSW164PGI7D77K" FOREIGN KEY ("PTS_STANDARD_REMARK")
	  REFERENCES "COMPASS_MI"."PTS_STANDARD_REMARK" ("GUID") ENABLE;

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" ADD CONSTRAINT "FK_OJVAKSGSPY80Q888MU0898SQ8" FOREIGN KEY ("PTS_GUID")
	  REFERENCES "COMPASS_MI"."PTS" ("GUID") ENABLE;

  ALTER TABLE "COMPASS_MI"."PTS_SERVICE_COMBO" ADD CONSTRAINT "FK_T5CNV5GNV6AOVOTYEPCQ5FNO9" FOREIGN KEY ("PTS_MODIFIER")
	  REFERENCES "COMPASS_MI"."PTS_MODIFIER" ("GUID") ENABLE;
