--------------------------------------------------------
--  File created - Wednesday-September-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICE_DEFINITION
--------------------------------------------------------

  CREATE TABLE "COMPASS_MI"."SERVICE_DEFINITION" 
   (	"GUID" RAW(16), 
	"VERSION" NUMBER(10,0), 
	"VENDOR" RAW(16), 
	"PTS_FS_SERVICE_COMBO" RAW(16), 
	"START_DATE" TIMESTAMP (6), 
	"EPISODE_GUID" RAW(16), 
	"SERVICE_DEFINITION_LINE" NUMBER(19,0), 
	"STOP_DATE" TIMESTAMP (6), 
	"NOTES_TO_VENDOR" CLOB
   );
--------------------------------------------------------
--  DDL for Index UK_JSKKF8LFCTQP47G83SE16X7DK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."UK_JSKKF8LFCTQP47G83SE16X7DK" ON "COMPASS_MI"."SERVICE_DEFINITION" ("VENDOR", "PTS_FS_SERVICE_COMBO", "START_DATE", "EPISODE_GUID") ;
--------------------------------------------------------
--  DDL for Index IDXSERVICE_DEFINITIONEPISODE
--------------------------------------------------------

  CREATE INDEX "COMPASS_MI"."IDXSERVICE_DEFINITIONEPISODE" ON "COMPASS_MI"."SERVICE_DEFINITION" ("VENDOR", "PTS_FS_SERVICE_COMBO", "EPISODE_GUID") ;
--------------------------------------------------------
--  DDL for Index SYS_C0015511
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPASS_MI"."SYS_C0015511" ON "COMPASS_MI"."SERVICE_DEFINITION" ("GUID") ;
--------------------------------------------------------
--  Constraints for Table SERVICE_DEFINITION
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("GUID" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("VERSION" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("VENDOR" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("PTS_FS_SERVICE_COMBO" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("EPISODE_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" MODIFY ("SERVICE_DEFINITION_LINE" NOT NULL ENABLE);
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" ADD PRIMARY KEY ("GUID");
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" ADD CONSTRAINT "UK_JSKKF8LFCTQP47G83SE16X7DK" UNIQUE ("VENDOR", "PTS_FS_SERVICE_COMBO", "START_DATE", "EPISODE_GUID");
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_DEFINITION
--------------------------------------------------------

  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" ADD CONSTRAINT "FK_CX1YMNC2NVOA6PRSVSIIQJQDY" FOREIGN KEY ("VENDOR")
	  REFERENCES "COMPASS_MI"."VENDOR" ("GUID") ENABLE;
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" ADD CONSTRAINT "FK_IG0CABDNMHDPU6E5YFI9I0F3M" FOREIGN KEY ("EPISODE_GUID")
	  REFERENCES "COMPASS_MI"."EPISODE" ("GUID") ENABLE;
 
  ALTER TABLE "COMPASS_MI"."SERVICE_DEFINITION" ADD CONSTRAINT "FK_IG0SEDQYG3B6Q61X5B38DS991" FOREIGN KEY ("PTS_FS_SERVICE_COMBO")
	  REFERENCES "COMPASS_MI"."PTS_FS_SERVICE_COMBO" ("GUID") ENABLE;
