--ALTER TABLE COMPASS_MI.PTS_STANDARD_REMARK DROP PRIMARY KEY CASCADE;
--
--DROP TABLE COMPASS_MI.PTS_STANDARD_REMARK CASCADE CONSTRAINTS;

CREATE TABLE COMPASS_MI.PTS_STANDARD_REMARK
(
  GUID         RAW(16)                          NOT NULL,
  VERSION      NUMBER(10)                       NOT NULL,
  CODE         VARCHAR2(4 CHAR)                 NOT NULL,
  PTS_GUID     RAW(16),
  DESCRIPTION  VARCHAR2(80 CHAR)                NOT NULL
);

CREATE INDEX COMPASS_MI.IDXPTS_STANDARD_REMARKPTS ON COMPASS_MI.PTS_STANDARD_REMARK(PTS_GUID);

CREATE UNIQUE INDEX COMPASS_MI.UKIDX_STD_REM_PTS_GUID ON COMPASS_MI.PTS_STANDARD_REMARK(CODE, PTS_GUID);

ALTER TABLE COMPASS_MI.PTS_STANDARD_REMARK ADD PRIMARY KEY (GUID);

ALTER TABLE COMPASS_MI.PTS_STANDARD_REMARK ADD  CONSTRAINT UK_STD_REM_PTS_GUID UNIQUE (CODE, PTS_GUID);

ALTER TABLE COMPASS_MI.PTS_STANDARD_REMARK ADD ( CONSTRAINT FK_STD_REM_PTS_GUID
 FOREIGN KEY (PTS_GUID)  REFERENCES COMPASS_MI.PTS (GUID));
